:: Place this file in the root project directory that has the .uproject file 
:: Deletes files that are automatically generated by Unreal. It does not delete the Saved folder. 
:: Then automatically starts up the CompanionTraversal project to be rebuilt. User must select yes or no for rebuild.

:: Delete Directories and Files if they exist
IF EXIST "Binaries" (
	rmdir /s /q "Binaries" 2>nul && (
		echo.
		echo.
		echo ******************************************
		echo Directory 'Binaries' deleted successfully.	
		echo ******************************************
		echo.
		echo.
	) || (
	echo Failed to delete the directory.
	)
) ELSE (
	echo.
	echo.
	echo -----------------------------------
	echo Directory 'Binaries' does not exist.
	echo -----------------------------------
)

IF EXIST "Intermediate" (
	rmdir /s /q "Intermediate" 2>nul && (
		echo.
		echo.
		echo ******************************************
		echo Directory 'Intermediate' deleted successfully.
		echo ******************************************
		echo.
		echo.
	) || (
	echo Failed to delete the directory.
	)
) ELSE (
	echo.
	echo.
	echo -----------------------------------
	echo Directory 'Intermediate' does not exist.
	echo -----------------------------------
)

IF EXIST "DerivedDataCache" (
	rmdir /s /q "DerivedDataCache" 2>nul && (
		echo.
		echo.
		echo ******************************************
		echo Directory 'DerivedDataCache' deleted successfully.
		echo ******************************************
		echo.
		echo.
	) || (
	echo Failed to delete the directory.
	)
) ELSE (
	echo.
	echo.
	echo -----------------------------------
	echo Directory 'DerivedDataCache' does not exist.
	echo -----------------------------------
)

IF EXIST "CompanionTraversal.sln" (
	del "CompanionTraversal.sln" 2>nul && (
		echo.
		echo.
		echo ******************************************
		echo File "CompanionTraversal.sln deleted successfully.
		echo ******************************************
		echo.
		echo.
	) || (
	echo Failed to delete the directory.
	)
) ELSE (
	echo.
	echo.
	echo -----------------------------------
	echo File 'CompanionTraversal.sln' does not exist.
	echo -----------------------------------
)

::Timeout for 2 second
	timeout 2
	
:: start editor
	start "CompanionTraversal" "CompanionTraversal.uproject"
